@echo off
echo Ajout des fichiers...
git add .
echo Creation du commit...
git commit -m "Optimisation de l'initialisation de la base de données et mises à jour"
echo Recuperation des modifications depuis GitHub...
git pull origin main --no-edit
echo Envoi vers la branche main...
git push origin main
pause